# Generated by Django 3.1.1 on 2020-09-13 05:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='record creation date',
                                                       verbose_name='creation date')),
                ('created_by', models.CharField(help_text='username that created the record', max_length=100,
                                                verbose_name='username created')),
                ('update_date',
                 models.DateTimeField(auto_now=True, help_text='record update date', verbose_name='update date')),
                ('update_by', models.CharField(help_text='username that updated the record', max_length=100,
                                               verbose_name='username updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False,
                                        verbose_name='id')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('photo', models.ImageField(upload_to='book/author', verbose_name='photo')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='record creation date',
                                                       verbose_name='creation date')),
                ('created_by', models.CharField(help_text='username that created the record', max_length=100,
                                                verbose_name='username created')),
                ('update_date',
                 models.DateTimeField(auto_now=True, help_text='record update date', verbose_name='update date')),
                ('update_by', models.CharField(help_text='username that updated the record', max_length=100,
                                               verbose_name='username updated')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('description', models.CharField(max_length=50, verbose_name='description')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='record creation date',
                                                       verbose_name='creation date')),
                ('created_by', models.CharField(help_text='username that created the record', max_length=100,
                                                verbose_name='username created')),
                ('update_date',
                 models.DateTimeField(auto_now=True, help_text='record update date', verbose_name='update date')),
                ('update_by', models.CharField(help_text='username that updated the record', max_length=100,
                                               verbose_name='username updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False,
                                        verbose_name='id')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('summary', models.TextField(max_length=300, verbose_name='summary')),
                ('cover', models.ImageField(upload_to='book/book', verbose_name='cover')),
                ('file', models.FileField(upload_to='book/book', verbose_name='file')),
                ('pages', models.PositiveSmallIntegerField(verbose_name='pages')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('categories', models.ManyToManyField(blank=True, related_name='categories', to='books.Category',
                                                      verbose_name='categories')),
                ('tags',
                 models.ManyToManyField(blank=True, related_name='tags', to='books.Category', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
    ]
